name: Build Matrix
on:
  workflow_call:
    inputs:
      package-json-path:
        description: 'Path to binding `package.json`. This option is the same as `--package-json-path` in `@napi-rs/cli build`.'
        required: false
        default: 'crates/binding/package.json'
        type: string
      napi-build-command:
        description: 'Command to call `napi build`. Use this option as an alias to build napi binding package. The directory of the package.json file is the working directory of the command.'
        required: false
        default: 'pnpm build'
        type: string
      working-directory:
        description: 'The working directory for all commands'
        required: false
        default: '.'
        type: string

env:
  DEBUG: napi:*
  MACOSX_DEPLOYMENT_TARGET: '10.13'
  CARGO_INCREMENTAL: '1'

permissions:
  contents: read

jobs:
  get-napi-info:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.napi-info.outputs.matrix }}
      binding-directory: ${{ steps.napi-info.outputs.binding-directory }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - name: Checkout rspack toolchain
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          repository: ${{ job.workflow_repository }}
          ref: ${{ job.workflow_sha }}
          path: .rspack-toolchain
          persist-credentials: false
      - name: Get NAPI Info
        id: napi-info
        uses: ./.rspack-toolchain/get-napi-info
        with:
          package-json-path: ${{ inputs.package-json-path }}
          napi-build-command: ${{ inputs.napi-build-command }}

  build:
    needs: get-napi-info
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.get-napi-info.outputs.matrix) }}
    name: build - ${{ matrix.settings.target }}
    runs-on: ${{ matrix.settings.host }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - name: setup pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '22'
          cache: pnpm
      - name: Setup node x86
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        if: matrix.settings.target == 'i686-pc-windows-msvc'
        with:
          node-version: '22'
          cache: pnpm
          architecture: x86
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
      # Skip installing Rust target when using cross as it manages targets internally
      # See: https://github.com/cross-rs/cross/blob/main/docs/getting-started.md?plain=1#L113
      - name: Install additional Rust target
        if: ${{ !contains(matrix.settings.build, 'use-cross') }}
        run: rustup target add ${{ matrix.settings.target }}
        working-directory: ${{ inputs.working-directory }}
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        with:
          key: ${{ matrix.settings.target }}
          cache-directories: |
            ~/.napi-rs
            .cargo-cache
      - name: Setup Zig for musl builds
        if: ${{ contains(matrix.settings.target, 'musl') }}
        uses: goto-bus-stop/setup-zig@abea47f85e598557f500fa1fd2ab7464fcb39406 # v2
        with:
          version: 0.13.0
      - name: Install cargo-zigbuild
        if: ${{ contains(matrix.settings.target, 'musl') }}
        uses: taiki-e/install-action@920ab1831fbf4fb3ef75c8ead83556c918bb7290 # v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tool: cargo-zigbuild
      - name: Install cross
        if: ${{ contains(matrix.settings.build, 'use-cross') }}
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Install dependencies
        run: pnpm install
        working-directory: ${{ inputs.working-directory }}
      - name: Build
        run: ${{ matrix.settings.build }}
        working-directory: ${{ needs.get-napi-info.outputs.binding-directory }}
        shell: bash
      - name: Upload artifact (node files)
        if: ${{ matrix.settings.target != 'wasm32-wasip1-threads' }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: bindings-${{ matrix.settings.target }}
          path: '${{ needs.get-napi-info.outputs.binding-directory }}/*.node'
          if-no-files-found: error
      # - name: Upload artifact (wasm files)
      #   if: ${{ matrix.settings.target == 'wasm32-wasip1-threads' }}
      #   uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      #   with:
      #     name: bindings-${{ matrix.settings.target }}
      #     path: '${{ needs.get-napi-info.outputs.binding-directory }}/*.wasm'
      #     if-no-files-found: error
